#include <stdio.h>
#include <stdlib.h>
#include "ppm.h"

#define PPM_VERBOSE_ERRORS

#define BYTES_PER_PIXEL 3
#define MAX_LINE_LEN 1024

/**
 * Load a PPM from a file into memory
 */
struct ppm *ppm_read(char *filename)
{
    FILE *fp;

    if ((fp = fopen(filename, "rb")) == NULL) {
#ifdef PPM_VERBOSE_ERRORS
        fprintf(stderr, "ppm_read: error opening file: \"%s\"\n", filename);
#endif
        return NULL;
    }

    char line[MAX_LINE_LEN];
    int type, width, height, maxval;
    int line_count = 0, count;

    while (line_count < 3) {
        if (fgets(line, MAX_LINE_LEN, fp) == NULL) {
#ifdef PPM_VERBOSE_ERRORS
            fprintf(stderr, "ppm_read: EOF in header\n");
#endif
            goto bail_error_1;
        }

        if (line[0] == '#')
            continue;

        switch (line_count) {
            case 0:
                count = sscanf(line, " P%d", &type);
                if (count != 1) {
#ifdef PPM_VERBOSE_ERRORS
                    fprintf(stderr, "ppm_read: error reading type: \"%s\"\n", line);
#endif
                    goto bail_error_1;
                }
                if (type != 6) {
#ifdef PPM_VERBOSE_ERRORS
                    fprintf(stderr, "ppm_read: only type 6 supported: \"%s\"\n", line);
#endif
                    goto bail_error_1;
                }
                break;

            case 1:
                count = sscanf(line, " %d %d", &width, &height);
                if (count != 2) {
#ifdef PPM_VERBOSE_ERRORS
                    fprintf(stderr, "ppm_read: error reading dimensions: \"%s\"\n", line);
#endif
                    goto bail_error_1;
                }
                break;

            case 2:
                count = sscanf(line, " %d", &maxval);
                if (count != 1) {
#ifdef PPM_VERBOSE_ERRORS
                    fprintf(stderr, "ppm_read: error reading max value: \"%s\"\n", line);
#endif
                    goto bail_error_1;
                }
                break;
        }

        line_count++;
    }

    int pixel_count = width * height;

    struct ppm *ppm = malloc(sizeof *ppm);

    if (ppm == NULL) {
#ifdef PPM_VERBOSE_ERRORS
        fprintf(stderr, "ppm_read: error allocating struct\n");
#endif
        goto bail_error_1;
    }

    ppm->type = type;
    ppm->width = width;
    ppm->height = height;
    ppm->maxval = maxval;
    ppm->data = malloc(pixel_count * BYTES_PER_PIXEL);

    if (ppm->data == NULL) {
#ifdef PPM_VERBOSE_ERRORS
        fprintf(stderr, "ppm_read: error allocating pixel data\n");
#endif
        goto bail_error_2;
    }

    for (int i = 0; i < pixel_count; i++) {
        int offset = i * BYTES_PER_PIXEL;
        if ((count = fread(ppm->data + offset, sizeof(char), BYTES_PER_PIXEL, fp)) != BYTES_PER_PIXEL) {
#ifdef PPM_VERBOSE_ERRORS
            fprintf(stderr, "ppm_read: error reading pixel data: count: %d\n", count);
#endif
            goto bail_error_3;
        }
    }

    fclose(fp);
    return ppm;

bail_error_3:
    free(ppm->data);

bail_error_2:
    free(ppm);

bail_error_1:
    fclose(fp);
    return NULL;
}

int ppm_write(struct ppm *ppm, char *filename)
{
    FILE *fp;

    if ((fp = fopen(filename, "wb")) == NULL) {
#ifdef PPM_VERBOSE_ERRORS
            fprintf(stderr, "ppm_write: error opening file %s\n", filename);
#endif
            return -1;
    }

    fprintf(fp, "P6\n");
    fprintf(fp, "# Generated by Beej's half-assed PPM lib\n");
    fprintf(fp, "%d %d\n", ppm->width, ppm->height);
    fprintf(fp, "%d\n", ppm->maxval);

    int pixel_count = ppm->width * ppm->height;
    int byte_count = pixel_count * BYTES_PER_PIXEL;

    int count = fwrite(ppm->data, sizeof(char), byte_count, fp);

    if (count != byte_count) {
#ifdef PPM_VERBOSE_ERRORS
        fprintf(stderr, "ppm_write: error: short write %d of %d\n", count, byte_count);
#endif
        goto bail_error;
    }

    return 0;
    
bail_error:
    fclose(fp);
    return -1;
}

void ppm_free(struct ppm *ppm) {
    free(ppm->data);
    free(ppm);
}

int ppm_get_pixel(struct ppm *ppm, int x, int y)
{
    if (x < 0 || y < 0 || x >= ppm->width || y >= ppm->height)
        return -1;

    int i = (y * ppm->width + x) * BYTES_PER_PIXEL;
    char *d = ppm->data;
    
    return PPM_PIXEL(d[i], d[i+1], d[i+2]);
}

void ppm_set_pixel(struct ppm *ppm, int x, int y, int pixel)
{
    if (x < 0 || y < 0 || x >= ppm->width || y >= ppm->height)
        return;

    int i = (y * ppm->width + x) * BYTES_PER_PIXEL;
    char *d = ppm->data;

    d[i] = PPM_PIXEL_R(pixel);
    d[i+1] = PPM_PIXEL_G(pixel);
    d[i+2] = PPM_PIXEL_B(pixel);
}

